In [67]:
import pandas as pd
import numpy as np
import json, re

In [68]:
spy_data = pd.read_csv('SPY_profils_normalized_v4.csv')

FileNotFoundError: [Errno 2] No such file or directory: 'SPY_profils_normalized_v4.csv'

In [ ]:
spy_data.head()

,ID,Class,IsTeacher,Progression,HighScore,LastUpdate
0,103D4EAB,3ème,0,"{""0 - Tutoriel"":1,""1 - Explorateur"":9,""2 - Col...","{""Levels\/Tutoriel\/Tutoriel.xml"":3,""Levels\/E...",2023-05-25 09:52:32
1,133323C,5ème,0,"{""0 - Tutoriel"":1,""1 - Explorateur"":9,""2 - Col...","{""Levels\/Tutoriel\/Tutoriel.xml"":3,""Levels\/E...",2023-05-30 09:50:07
2,1410D322,4ème,0,"{""0 - Tutoriel"":1,""1 - Explorateur"":9,""2 - Col...","{""Levels\/Tutoriel\/Tutoriel.xml"":3,""Levels\/E...",2023-10-06 15:19:12
3,149C46A2,4ème,0,"{""0 - Tutoriel"":1,""1 - Explorateur"":9,""2 - Col...","{""Levels\/Tutoriel\/Tutoriel.xml"":3,""Levels\/E...",2023-06-15 09:55:08
4,14A766E2,CM2,0,"{""0 - Tutoriel"":1,""1 - Explorateur"":9,""2 - Col...","{""Levels\/Tutoriel\/Tutoriel.xml"":3,""Levels\/E...",2023-05-25 13:57:30

In [ ]:
import json

progress = spy_data['Progression']

NbLevels = []

for j in progress:
    j = json.loads(j)
    nbLevel = 0
    
    for level in j.values():
        nbLevel += int(level)
    
    #print(nbLevel)
    NbLevels.append(nbLevel)

spy_data['NbLevels'] = NbLevels

In [ ]:
spy_data.head()

,ID,Class,IsTeacher,Progression,HighScore,LastUpdate,NbLevels
0,103D4EAB,3ème,0,"{""0 - Tutoriel"":1,""1 - Explorateur"":9,""2 - Col...","{""Levels\/Tutoriel\/Tutoriel.xml"":3,""Levels\/E...",2023-05-25 09:52:32,12
1,133323C,5ème,0,"{""0 - Tutoriel"":1,""1 - Explorateur"":9,""2 - Col...","{""Levels\/Tutoriel\/Tutoriel.xml"":3,""Levels\/E...",2023-05-30 09:50:07,38
2,1410D322,4ème,0,"{""0 - Tutoriel"":1,""1 - Explorateur"":9,""2 - Col...","{""Levels\/Tutoriel\/Tutoriel.xml"":3,""Levels\/E...",2023-10-06 15:19:12,11
3,149C46A2,4ème,0,"{""0 - Tutoriel"":1,""1 - Explorateur"":9,""2 - Col...","{""Levels\/Tutoriel\/Tutoriel.xml"":3,""Levels\/E...",2023-06-15 09:55:08,18
4,14A766E2,CM2,0,"{""0 - Tutoriel"":1,""1 - Explorateur"":9,""2 - Col...","{""Levels\/Tutoriel\/Tutoriel.xml"":3,""Levels\/E...",2023-05-25 13:57:30,31

In [ ]:
spy_data = pd.read_csv('full_spy_data.csv')

In [ ]:
spy_data.head()

,_id,version,id,timestamp,stored,actor,verb,object,result,authority,context
0,652d32344c323c03df9ca1de,1.0.1,2ad6dd87-a685-4807-9365-5e47a09c0faf,2023-10-16T12:52:23.9850000Z,2023-10-16T12:53:07.826Z,"{""objectType"":""Agent"",""name"":""C1E0F8B9"",""accou...","{""id"":""http://adlnet.gov/expapi/verbs/exited"",...","{""objectType"":""Activity"",""id"":""https://w3id.or...",NaN,"{""objectType"":""Agent"",""name"":""New Client"",""mbo...",NaN
1,652d32344c323c03df9ca1dd,1.0.1,66ba3816-0f60-4776-bfdb-9836c02fd92a,2023-10-16T12:52:14.3070000Z,2023-10-16T12:53:07.826Z,"{""objectType"":""Agent"",""name"":""C1E0F8B9"",""accou...","{""id"":""http://adlnet.gov/expapi/verbs/interact...","{""objectType"":""Activity"",""id"":""https://spy.lip...",NaN,"{""objectType"":""Agent"",""name"":""New Client"",""mbo...",NaN
2,652d32344c323c03df9ca1dc,1.0.1,b344c16c-5223-46ec-a3f5-f6e73f5e0b19,2023-10-16T12:52:10.5780000Z,2023-10-16T12:53:07.826Z,"{""objectType"":""Agent"",""name"":""C1E0F8B9"",""accou...","{""id"":""http://adlnet.gov/expapi/verbs/interact...","{""objectType"":""Activity"",""id"":""https://spy.lip...",NaN,"{""objectType"":""Agent"",""name"":""New Client"",""mbo...",NaN
3,652d32344c323c03df9ca1db,1.0.1,4a6e5a4b-35a7-4c24-8b6f-554744fcef58,2023-10-16T12:52:08.8620000Z,2023-10-16T12:53:07.826Z,"{""objectType"":""Agent"",""name"":""C1E0F8B9"",""accou...","{""id"":""http://adlnet.gov/expapi/verbs/interact...","{""objectType"":""Activity"",""id"":""https://spy.lip...",NaN,"{""objectType"":""Agent"",""name"":""New Client"",""mbo...",NaN
4,652d32344c323c03df9ca1da,1.0.1,6d44d933-41af-40ed-8486-faeb72d28666,2023-10-16T12:52:07.6800000Z,2023-10-16T12:53:07.826Z,"{""objectType"":""Agent"",""name"":""C1E0F8B9"",""accou...","{""id"":""http://adlnet.gov/expapi/verbs/interact...","{""objectType"":""Activity"",""id"":""https://spy.lip...",NaN,"{""objectType"":""Agent"",""name"":""New Client"",""mbo...",NaN

In [ ]:
clean_spy_data = pd.DataFrame()

In [ ]:
actors = spy_data['actor']

clean_actors = []
for actor in actors:
    a = json.loads(actor)
    clean_actors.append(a['name'])

In [ ]:
clean_spy_data['actor'] = clean_actors

In [ ]:
clean_spy_data['timestamp'] = spy_data['timestamp']
clean_spy_data['stored'] = spy_data['stored']

In [ ]:
clean_spy_data

           actor                     timestamp                    stored
0       C1E0F8B9  2023-10-16T12:52:23.9850000Z  2023-10-16T12:53:07.826Z
1       C1E0F8B9  2023-10-16T12:52:14.3070000Z  2023-10-16T12:53:07.826Z
2       C1E0F8B9  2023-10-16T12:52:10.5780000Z  2023-10-16T12:53:07.826Z
3       C1E0F8B9  2023-10-16T12:52:08.8620000Z  2023-10-16T12:53:07.826Z
4       C1E0F8B9  2023-10-16T12:52:07.6800000Z  2023-10-16T12:53:07.826Z
...          ...                           ...                       ...
327396  743DB88B  2023-01-06T15:26:56.4810000Z  2023-01-06T15:27:02.552Z
327397  F9812AA6  2023-01-04T13:44:27.6830000Z  2023-01-04T13:44:37.440Z
327398  F9812AA6  2023-01-04T13:44:27.5600000Z  2023-01-04T13:44:37.440Z
327399  743DB88B  2022-12-20T11:03:02.5100000Z  2022-12-20T11:03:05.312Z
327400  743DB88B  2022-12-20T11:03:02.0810000Z  2022-12-20T11:03:05.312Z

[327401 rows x 3 columns]

In [ ]:
actors = spy_data['verb']

clean_verbs = []
for actor in actors:
    a = json.loads(actor)
    clean_verbs.append(a['display']['en-US'])

clean_spy_data['verbs'] = clean_verbs

In [ ]:
clean_spy_data.head()

,actor,timestamp,stored,verbs
0,C1E0F8B9,2023-10-16T12:52:23.9850000Z,2023-10-16T12:53:07.826Z,exited
1,C1E0F8B9,2023-10-16T12:52:14.3070000Z,2023-10-16T12:53:07.826Z,interacted
2,C1E0F8B9,2023-10-16T12:52:10.5780000Z,2023-10-16T12:53:07.826Z,interacted
3,C1E0F8B9,2023-10-16T12:52:08.8620000Z,2023-10-16T12:53:07.826Z,interacted
4,C1E0F8B9,2023-10-16T12:52:07.6800000Z,2023-10-16T12:53:07.826Z,interacted

In [ ]:
actors = spy_data['object']

clean_verbs = []
for actor in actors:
    a = json.loads(actor)
    if a['objectType'] == 'Activity':
        clean_verbs.append(a['definition']['name']['en-US'])

clean_spy_data['object'] = clean_verbs

In [ ]:
clean_spy_data.head()

,actor,timestamp,stored,verbs,object
0,C1E0F8B9,2023-10-16T12:52:23.9850000Z,2023-10-16T12:53:07.826Z,exited,level
1,C1E0F8B9,2023-10-16T12:52:14.3070000Z,2023-10-16T12:53:07.826Z,interacted,camera
2,C1E0F8B9,2023-10-16T12:52:10.5780000Z,2023-10-16T12:53:07.826Z,interacted,camera
3,C1E0F8B9,2023-10-16T12:52:08.8620000Z,2023-10-16T12:53:07.826Z,interacted,camera
4,C1E0F8B9,2023-10-16T12:52:07.6800000Z,2023-10-16T12:53:07.826Z,interacted,camera

In [ ]:
actors = spy_data['object']

clean_levels = []

pattern = r"/niveau(\d+)\.xml$"

for actor in actors:
    a = json.loads(actor)
    if a['objectType'] == 'Activity':
        if a['definition']['name']['en-US'] == 'level':
            try:
                chemin = list(a['definition']['extensions'].values())[0][0][:-4]
                clean_levels.append(chemin)
            except:
                clean_levels.append('')
        else:
            clean_levels.append('')
    else:
        clean_levels.append('')

clean_spy_data['levels'] = clean_levels

In [ ]:
clean_spy_data[:20]

,actor,timestamp,stored,verbs,object,levels,results
0,C1E0F8B9,2023-10-16T12:52:23.9850000Z,2023-10-16T12:53:07.826Z,exited,level,levels/explorateur/niveau03,
1,C1E0F8B9,2023-10-16T12:52:14.3070000Z,2023-10-16T12:53:07.826Z,interacted,camera,,
2,C1E0F8B9,2023-10-16T12:52:10.5780000Z,2023-10-16T12:53:07.826Z,interacted,camera,,
3,C1E0F8B9,2023-10-16T12:52:08.8620000Z,2023-10-16T12:53:07.826Z,interacted,camera,,
4,C1E0F8B9,2023-10-16T12:52:07.6800000Z,2023-10-16T12:53:07.826Z,interacted,camera,,
5,C1E0F8B9,2023-10-16T12:52:06.3650000Z,2023-10-16T12:53:07.826Z,interacted,camera,,
6,C1E0F8B9,2023-10-16T12:52:04.7320000Z,2023-10-16T12:53:07.826Z,interacted,camera,,
7,C1E0F8B9,2023-10-16T12:52:02.1180000Z,2023-10-16T12:53:07.826Z,interacted,camera,,
8,C1E0F8B9,2023-10-16T12:52:00.2860000Z,2023-10-16T12:53:07.826Z,interacted,camera,,
9,C1E0F8B9,2023-10-16T12:51:56.4980000Z,2023-10-16T12:53:07.826Z,launched,level,levels/explorateur/niveau03,
10,C1E0F8B9,2023-10-16T12:51:56.3570000Z,2023-10-16T12:53:07.826Z,exited,level,levels/explorateur/niveau02,
11,C1E0F8B9,2023-10-16T12:51:54.5070000Z,2023-10-16T12:52:25.109Z,completed,level,,
12,C1E0F8B9,2023-10-16T12:51:52.3930000Z,2023-10-16T12:52:25.109Z,executed,program,,
13,C1E0F8B9,2023-10-16T12:51:48.1160000Z,2023-10-16T12:52:25.109Z,inserted,block,,
14,C1E0F8B9,2023-10-16T12:51:46.3170000Z,2023-10-16T12:52:25.109Z,inserted,block,,
15,C1E0F8B9,2023-10-16T12:51:39.7910000Z,2023-10-16T12:52:25.109Z,launched,level,levels/explorateur/niveau02,
16,C1E0F8B9,2023-10-16T12:51:39.6550000Z,2023-10-16T12:52:25.109Z,exited,level,levels/explorateur/niveau01,
17,C1E0F8B9,2023-10-16T12:51:37.7100000Z,2023-10-16T12:52:08.321Z,completed,level,,
18,C1E0F8B9,2023-10-16T12:51:36.6000000Z,2023-10-16T12:52:08.293Z,executed,program,,
19,C1E0F8B9,2023-10-16T12:51:26.9970000Z,2023-10-16T12:52:08.293Z,interacted,camera,,

In [ ]:
clean_spy_data[clean_spy_data['verbs'] == 'completed']

,actor,timestamp,stored,verbs,object,levels,results
11,C1E0F8B9,2023-10-16T12:51:54.5070000Z,2023-10-16T12:52:25.109Z,completed,level,,
17,C1E0F8B9,2023-10-16T12:51:37.7100000Z,2023-10-16T12:52:08.321Z,completed,level,,
26,C1E0F8B9,2023-10-16T12:50:41.5770000Z,2023-10-16T12:51:12.207Z,completed,level,,
67,EE71EF2,2023-10-15T14:27:40.1210000Z,2023-10-15T14:28:12.728Z,completed,level,,
84,EE71EF2,2023-10-15T14:25:06.0430000Z,2023-10-15T14:25:39.481Z,completed,level,,
...,...,...,...,...,...,...,...
327350,F8D49C55,2023-01-06T18:14:47.4250000Z,2023-01-06T18:15:29.651Z,completed,level,,
327360,F8D49C55,2023-01-06T18:14:12.9350000Z,2023-01-06T18:15:29.651Z,completed,level,,
327369,F8D49C55,2023-01-06T18:13:45.8350000Z,2023-01-06T18:15:29.651Z,completed,level,,
327378,86D3E3AC,2023-01-06T17:03:22.0080000Z,2023-01-06T17:04:23.599Z,completed,level,,
327387,86D3E3AC,2023-01-06T17:01:52.3470000Z,2023-01-06T17:04:23.599Z,completed,level,,

In [ ]:
actors = spy_data['object']

clean_results = []
i = 0
for actor in actors:
    a = json.loads(actor)
    try:
        if spy_data[i]['verbs'] == 'completed':
            print('complete')
        print(a['statement']['result']['success'])
        clean_results.append(a['statement']['result']['success'])
        break
    except:
        clean_results.append('')
    i+= 1

clean_spy_data['results'] = clean_results

In [ ]:
clean_spy_data.loc[clean_spy_data['verbs'] == 'completed']

,actor,timestamp,stored,verbs,object,levels,results
11,C1E0F8B9,2023-10-16T12:51:54.5070000Z,2023-10-16T12:52:25.109Z,completed,level,,
17,C1E0F8B9,2023-10-16T12:51:37.7100000Z,2023-10-16T12:52:08.321Z,completed,level,,
26,C1E0F8B9,2023-10-16T12:50:41.5770000Z,2023-10-16T12:51:12.207Z,completed,level,,
67,EE71EF2,2023-10-15T14:27:40.1210000Z,2023-10-15T14:28:12.728Z,completed,level,,
84,EE71EF2,2023-10-15T14:25:06.0430000Z,2023-10-15T14:25:39.481Z,completed,level,,
...,...,...,...,...,...,...,...
327350,F8D49C55,2023-01-06T18:14:47.4250000Z,2023-01-06T18:15:29.651Z,completed,level,,
327360,F8D49C55,2023-01-06T18:14:12.9350000Z,2023-01-06T18:15:29.651Z,completed,level,,
327369,F8D49C55,2023-01-06T18:13:45.8350000Z,2023-01-06T18:15:29.651Z,completed,level,,
327378,86D3E3AC,2023-01-06T17:03:22.0080000Z,2023-01-06T17:04:23.599Z,completed,level,,
327387,86D3E3AC,2023-01-06T17:01:52.3470000Z,2023-01-06T17:04:23.599Z,completed,level,,

In [ ]:
clean_spy_data.to_csv('spy_test.csv')

NameError: name 'clean_spy_data' is not defined

In [ ]:
spy_data = pd.read_csv('spy_test_updated.csv')

In [ ]:
current_level = None

i = 0

for index, row in spy_data.iloc[::-1].iterrows():
    
    if (row['verbs'] == 'launched' and current_level) or row['verbs'] == 'exited':
        current_level = None
    if row['verbs'] == 'launched':
        current_level = row['levels']
    
    if current_level:
        spy_data.at[index, 'levels'] = current_level
    
    i += 1

In [ ]:
spy_data.to_csv('clean_spy_data.csv')

In [ ]:
raw_spy_data = pd.read_csv('full_spy_data.csv')
clean_spy_data = pd.read_csv('clean_spy_data.csv')

In [ ]:
clean_results = []

for index, row in raw_spy_data.iterrows():
    if isinstance(row['result'], str) or not np.isnan(row['result']):
        j = json.loads(row['result'])

        clean_results.append(j['success'])
    else:
        clean_results.append('')

clean_spy_data['results'] = clean_results

NameError: name 'raw_spy_data' is not defined

In [ ]:
clean_spy_data.to_csv('clean_spy_data.csv')

NameError: name 'clean_spy_data' is not defined

In [ ]:
display(clean_spy_data[clean_spy_data['actor'] == 'C1E0F8B9'])

,Unnamed: 0.1,Unnamed: 0,actor,timestamp,stored,verbs,object,levels,results
0,0,0,C1E0F8B9,2023-10-16T12:52:23.9850000Z,2023-10-16T12:53:07.826Z,exited,level,levels/explorateur/niveau03,
1,1,1,C1E0F8B9,2023-10-16T12:52:14.3070000Z,2023-10-16T12:53:07.826Z,interacted,camera,levels/explorateur/niveau03,
2,2,2,C1E0F8B9,2023-10-16T12:52:10.5780000Z,2023-10-16T12:53:07.826Z,interacted,camera,levels/explorateur/niveau03,
3,3,3,C1E0F8B9,2023-10-16T12:52:08.8620000Z,2023-10-16T12:53:07.826Z,interacted,camera,levels/explorateur/niveau03,
4,4,4,C1E0F8B9,2023-10-16T12:52:07.6800000Z,2023-10-16T12:53:07.826Z,interacted,camera,levels/explorateur/niveau03,
5,5,5,C1E0F8B9,2023-10-16T12:52:06.3650000Z,2023-10-16T12:53:07.826Z,interacted,camera,levels/explorateur/niveau03,
6,6,6,C1E0F8B9,2023-10-16T12:52:04.7320000Z,2023-10-16T12:53:07.826Z,interacted,camera,levels/explorateur/niveau03,
7,7,7,C1E0F8B9,2023-10-16T12:52:02.1180000Z,2023-10-16T12:53:07.826Z,interacted,camera,levels/explorateur/niveau03,
8,8,8,C1E0F8B9,2023-10-16T12:52:00.2860000Z,2023-10-16T12:53:07.826Z,interacted,camera,levels/explorateur/niveau03,
9,9,9,C1E0F8B9,2023-10-16T12:51:56.4980000Z,2023-10-16T12:53:07.826Z,launched,level,levels/explorateur/niveau03,
10,10,10,C1E0F8B9,2023-10-16T12:51:56.3570000Z,2023-10-16T12:53:07.826Z,exited,level,levels/explorateur/niveau02,
11,11,11,C1E0F8B9,2023-10-16T12:51:54.5070000Z,2023-10-16T12:52:25.109Z,completed,level,levels/explorateur/niveau02,True
12,12,12,C1E0F8B9,2023-10-16T12:51:52.3930000Z,2023-10-16T12:52:25.109Z,executed,program,levels/explorateur/niveau02,
13,13,13,C1E0F8B9,2023-10-16T12:51:48.1160000Z,2023-10-16T12:52:25.109Z,inserted,block,levels/explorateur/niveau02,
14,14,14,C1E0F8B9,2023-10-16T12:51:46.3170000Z,2023-10-16T12:52:25.109Z,inserted,block,levels/explorateur/niveau02,
15,15,15,C1E0F8B9,2023-10-16T12:51:39.7910000Z,2023-10-16T12:52:25.109Z,launched,level,levels/explorateur/niveau02,
16,16,16,C1E0F8B9,2023-10-16T12:51:39.6550000Z,2023-10-16T12:52:25.109Z,exited,level,levels/explorateur/niveau01,
17,17,17,C1E0F8B9,2023-10-16T12:51:37.7100000Z,2023-10-16T12:52:08.321Z,completed,level,levels/explorateur/niveau01,True
18,18,18,C1E0F8B9,2023-10-16T12:51:36.6000000Z,2023-10-16T12:52:08.293Z,executed,program,levels/explorateur/niveau01,
19,19,19,C1E0F8B9,2023-10-16T12:51:26.9970000Z,2023-10-16T12:52:08.293Z,interacted,camera,levels/explorateur/niveau01,
20,20,20,C1E0F8B9,2023-10-16T12:51:25.8150000Z,2023-10-16T12:52:08.293Z,interacted,camera,levels/explorateur/niveau01,
21,21,21,C1E0F8B9,2023-10-16T12:51:19.7060000Z,2023-10-16T12:52:08.293Z,inserted,block,levels/explorateur/niveau01,
22,22,22,C1E0F8B9,2023-10-16T12:51:15.5420000Z,2023-10-16T12:52:08.293Z,closed,briefing,levels/explorateur/niveau01,
23,23,23,C1E0F8B9,2023-10-16T12:51:12.6980000Z,2023-10-16T12:52:08.293Z,opened,briefing,levels/explorateur/niveau01,
24,24,24,C1E0F8B9,2023-10-16T12:51:12.4670000Z,2023-10-16T12:52:08.293Z,launched,level,levels/explorateur/niveau01,
25,25,25,C1E0F8B9,2023-10-16T12:50:51.3780000Z,2023-10-16T12:52:08.293Z,exited,level,levels/tutoriel/tutoriel,
26,26,26,C1E0F8B9,2023-10-16T12:50:41.5770000Z,2023-10-16T12:51:12.207Z,completed,level,levels/tutoriel/tutoriel,True
27,27,27,C1E0F8B9,2023-10-16T12:50:40.4680000Z,2023-10-16T12:51:12.207Z,executed,program,levels/tutoriel/tutoriel,
28,28,28,C1E0F8B9,2023-10-16T12:50:35.1600000Z,2023-10-16T12:51:12.207Z,inserted,block,levels/tutoriel/tutoriel,
29,29,29,C1E0F8B9,2023-10-16T12:50:32.6610000Z,2023-10-16T12:51:12.207Z,closed,briefing,levels/tutoriel/tutoriel,
30,30,30,C1E0F8B9,2023-10-16T12:50:26.0500000Z,2023-10-16T12:51:12.207Z,interacted,briefing,levels/tutoriel/tutoriel,
31,31,31,C1E0F8B9,2023-10-16T12:50:16.2960000Z,2023-10-16T12:51:12.207Z,interacted,briefing,levels/tutoriel/tutoriel,
32,32,32,C1E0F8B9,2023-10-16T12:50:09.6510000Z,2023-10-16T12:51:12.207Z,interacted,briefing,levels/tutoriel/tutoriel,
33,33,33,C1E0F8B9,2023-10-16T12:49:56.8280000Z,2023-10-16T12:51:12.207Z,interacted,briefing,levels/tutoriel/tutoriel,
34,34,34,C1E0F8B9,2023-10-16T12:49:44.1230000Z,2023-10-16T12:51:12.207Z,interacted,briefing,levels/tutoriel/tutoriel,
35,35,35,C1E0F8B9,2023-10-16T12:49:33.1940000Z,2023-10-16T12:51:12.207Z,opened,briefing,levels/tutoriel/tutoriel,
36,36,36,C1E0F8B9,2023-10-16T12:49:32.9020000Z,2023-10-16T12:51:12.207Z,launched,level,levels/tutoriel/tutoriel,

In [ ]:
# Load Spy data
clean_spy_data = pd.read_csv('clean_spy_data.csv')

# Display data
display(clean_spy_data)

# Explore data
clean_spy_data['actor'].value_counts()

,Unnamed: 0.2,Unnamed: 0.1,Unnamed: 0,actor,timestamp,stored,verbs,object,levels,results
0,0,0,0,C1E0F8B9,2023-10-16T12:52:23.9850000Z,2023-10-16T12:53:07.826Z,exited,level,levels/explorateur/niveau03,NaN
1,1,1,1,C1E0F8B9,2023-10-16T12:52:14.3070000Z,2023-10-16T12:53:07.826Z,interacted,camera,levels/explorateur/niveau03,NaN
2,2,2,2,C1E0F8B9,2023-10-16T12:52:10.5780000Z,2023-10-16T12:53:07.826Z,interacted,camera,levels/explorateur/niveau03,NaN
3,3,3,3,C1E0F8B9,2023-10-16T12:52:08.8620000Z,2023-10-16T12:53:07.826Z,interacted,camera,levels/explorateur/niveau03,NaN
4,4,4,4,C1E0F8B9,2023-10-16T12:52:07.6800000Z,2023-10-16T12:53:07.826Z,interacted,camera,levels/explorateur/niveau03,NaN
...,...,...,...,...,...,...,...,...,...,...
327396,327396,327396,327396,743DB88B,2023-01-06T15:26:56.4810000Z,2023-01-06T15:27:02.552Z,launched,level,levels/infiltration/niveau01,NaN
327397,327397,327397,327397,F9812AA6,2023-01-04T13:44:27.6830000Z,2023-01-04T13:44:37.440Z,opened,briefing,levels/infiltration/niveau01,NaN
327398,327398,327398,327398,F9812AA6,2023-01-04T13:44:27.5600000Z,2023-01-04T13:44:37.440Z,launched,level,levels/infiltration/niveau01,NaN
327399,327399,327399,327399,743DB88B,2022-12-20T11:03:02.5100000Z,2022-12-20T11:03:05.312Z,opened,briefing,levels/infiltration/niveau01,NaN
327400,327400,327400,327400,743DB88B,2022-12-20T11:03:02.0810000Z,2022-12-20T11:03:05.312Z,launched,level,levels/infiltration/niveau01,NaN

A2592CC9    2800
96DD66C9    2777
FC5E2940    2318
FC5E2A23    2143
59B6B585    2052
            ...
ED6B2A         2
7364516E       2
139943E        2
F9812AA6       2
EE443408       1
Name: actor, Length: 781, dtype: int64

In [ ]:
clean_spy_data[:30]

,Unnamed: 0.2,Unnamed: 0.1,Unnamed: 0,actor,timestamp,stored,verbs,object,levels,results,time_spent
0,0,0,0,C1E0F8B9,2023-10-16T12:52:23.9850000Z,2023-10-16T12:53:07.826Z,exited,level,levels/explorateur/niveau03,NaN,0.000
1,1,1,1,C1E0F8B9,2023-10-16T12:52:14.3070000Z,2023-10-16T12:53:07.826Z,interacted,camera,levels/explorateur/niveau03,NaN,0.000
2,2,2,2,C1E0F8B9,2023-10-16T12:52:10.5780000Z,2023-10-16T12:53:07.826Z,interacted,camera,levels/explorateur/niveau03,NaN,0.000
3,3,3,3,C1E0F8B9,2023-10-16T12:52:08.8620000Z,2023-10-16T12:53:07.826Z,interacted,camera,levels/explorateur/niveau03,NaN,0.000
4,4,4,4,C1E0F8B9,2023-10-16T12:52:07.6800000Z,2023-10-16T12:53:07.826Z,interacted,camera,levels/explorateur/niveau03,NaN,0.000
5,5,5,5,C1E0F8B9,2023-10-16T12:52:06.3650000Z,2023-10-16T12:53:07.826Z,interacted,camera,levels/explorateur/niveau03,NaN,0.000
6,6,6,6,C1E0F8B9,2023-10-16T12:52:04.7320000Z,2023-10-16T12:53:07.826Z,interacted,camera,levels/explorateur/niveau03,NaN,0.000
7,7,7,7,C1E0F8B9,2023-10-16T12:52:02.1180000Z,2023-10-16T12:53:07.826Z,interacted,camera,levels/explorateur/niveau03,NaN,0.000
8,8,8,8,C1E0F8B9,2023-10-16T12:52:00.2860000Z,2023-10-16T12:53:07.826Z,interacted,camera,levels/explorateur/niveau03,NaN,0.000
9,9,9,9,C1E0F8B9,2023-10-16T12:51:56.4980000Z,2023-10-16T12:53:07.826Z,launched,level,levels/explorateur/niveau03,NaN,3.788
10,10,10,10,C1E0F8B9,2023-10-16T12:51:56.3570000Z,2023-10-16T12:53:07.826Z,exited,level,levels/explorateur/niveau02,NaN,0.000
11,11,11,11,C1E0F8B9,2023-10-16T12:51:54.5070000Z,2023-10-16T12:52:25.109Z,completed,level,levels/explorateur/niveau02,True,0.000
12,12,12,12,C1E0F8B9,2023-10-16T12:51:52.3930000Z,2023-10-16T12:52:25.109Z,executed,program,levels/explorateur/niveau02,NaN,0.000
13,13,13,13,C1E0F8B9,2023-10-16T12:51:48.1160000Z,2023-10-16T12:52:25.109Z,inserted,block,levels/explorateur/niveau02,NaN,0.000
14,14,14,14,C1E0F8B9,2023-10-16T12:51:46.3170000Z,2023-10-16T12:52:25.109Z,inserted,block,levels/explorateur/niveau02,NaN,0.000
15,15,15,15,C1E0F8B9,2023-10-16T12:51:39.7910000Z,2023-10-16T12:52:25.109Z,launched,level,levels/explorateur/niveau02,NaN,6.526
16,16,16,16,C1E0F8B9,2023-10-16T12:51:39.6550000Z,2023-10-16T12:52:25.109Z,exited,level,levels/explorateur/niveau01,NaN,0.000
17,17,17,17,C1E0F8B9,2023-10-16T12:51:37.7100000Z,2023-10-16T12:52:08.321Z,completed,level,levels/explorateur/niveau01,True,0.000
18,18,18,18,C1E0F8B9,2023-10-16T12:51:36.6000000Z,2023-10-16T12:52:08.293Z,executed,program,levels/explorateur/niveau01,NaN,0.000
19,19,19,19,C1E0F8B9,2023-10-16T12:51:26.9970000Z,2023-10-16T12:52:08.293Z,interacted,camera,levels/explorateur/niveau01,NaN,0.000
20,20,20,20,C1E0F8B9,2023-10-16T12:51:25.8150000Z,2023-10-16T12:52:08.293Z,interacted,camera,levels/explorateur/niveau01,NaN,0.000
21,21,21,21,C1E0F8B9,2023-10-16T12:51:19.7060000Z,2023-10-16T12:52:08.293Z,inserted,block,levels/explorateur/niveau01,NaN,0.000
22,22,22,22,C1E0F8B9,2023-10-16T12:51:15.5420000Z,2023-10-16T12:52:08.293Z,closed,briefing,levels/explorateur/niveau01,NaN,0.000
23,23,23,23,C1E0F8B9,2023-10-16T12:51:12.6980000Z,2023-10-16T12:52:08.293Z,opened,briefing,levels/explorateur/niveau01,NaN,0.000
24,24,24,24,C1E0F8B9,2023-10-16T12:51:12.4670000Z,2023-10-16T12:52:08.293Z,launched,level,levels/explorateur/niveau01,NaN,0.231
25,25,25,25,C1E0F8B9,2023-10-16T12:50:51.3780000Z,2023-10-16T12:52:08.293Z,exited,level,levels/tutoriel/tutoriel,NaN,0.000
26,26,26,26,C1E0F8B9,2023-10-16T12:50:41.5770000Z,2023-10-16T12:51:12.207Z,completed,level,levels/tutoriel/tutoriel,True,0.000
27,27,27,27,C1E0F8B9,2023-10-16T12:50:40.4680000Z,2023-10-16T12:51:12.207Z,executed,program,levels/tutoriel/tutoriel,NaN,0.000
28,28,28,28,C1E0F8B9,2023-10-16T12:50:35.1600000Z,2023-10-16T12:51:12.207Z,inserted,block,levels/tutoriel/tutoriel,NaN,0.000
29,29,29,29,C1E0F8B9,2023-10-16T12:50:32.6610000Z,2023-10-16T12:51:12.207Z,closed,briefing,levels/tutoriel/tutoriel,NaN,0.000

In [1]:
import pandas as pd
import numpy as np
import json, re

# Computing the time taken to finish a level.

To compute the time taken to finish a level, we can make the difference between the time of the last 'launched' verb and the time of the first 'completed' verb. We will put the time in a new column called 'time_taken', in a row with the verb 'completed'.

In [5]:
# Load Spy data
clean_spy_data = pd.read_csv('clean_spy_data.csv')

# Remove the unamed columns
clean_spy_data = clean_spy_data.loc[:, ~clean_spy_data.columns.str.contains('^Unnamed')]

# Sort data by actor and timestamp in reverse order
clean_spy_data = clean_spy_data.sort_values(by=['actor', 'timestamp'], ascending=False)

In [ ]:
# Make a variable to store the last level played.
current_level = None

# Loop through the data
for index, row in clean_spy_data.iloc[::-1].iterrows():
    # If the verb is 'launched' and the current level is not None, 
    # then we store the current level in the variable current_level
    if (row['verbs'] == 'launched' and current_level) or row['verbs'] == 'exited':
        current_level = None

# Save the data of f10c3152 
clean_spy_data[clean_spy_data['actor'] == 'f10c3152'].to_csv('f10c3152.csv')

KeyboardInterrupt:

In [ ]:
end_time = None
last_completed_index = None

# Iterate over data backwards
for index, row in clean_spy_data.iterrows():
    # If we encounter a 'completed' verb
    if row['verbs'] == 'completed':
        # Store the timestamp as the end time and convert it to a datetime object
        end_time = pd.to_datetime(row['timestamp'])
        
        # Store the index of the last completed verb
        last_completed_index = index

    # If we encounter a 'launched' verb
    if row['verbs'] == 'launched':
        # If we have an end time
        if end_time:
            # Store the start time and convert it to a datetime object
            start_time = pd.to_datetime(row['timestamp'])
            # Calculate the time taken and store it in the dataframe with the last completed verb
            clean_spy_data.at[last_completed_index, 'time_taken'] = (end_time - start_time).total_seconds()
            
            # Reset the end time
            end_time = None

In [42]:
# Load full spy data
spy_data = pd.read_csv('full_spy_data.csv')

# Temporary list of actors
actors = []

# Iterate over data 
for index, row in spy_data.iterrows():
    # Create a json object from the actor column
    a = json.loads(row['actor'])
    # Append the name of the actor to the list
    actors.append(a['name'])

spy_data['actor'] = actors

spy_data.head()

,_id,version,id,timestamp,stored,actor,verb,object,result,authority,context
0,652d32344c323c03df9ca1de,1.0.1,2ad6dd87-a685-4807-9365-5e47a09c0faf,2023-10-16T12:52:23.9850000Z,2023-10-16T12:53:07.826Z,C1E0F8B9,"{""id"":""http://adlnet.gov/expapi/verbs/exited"",...","{""objectType"":""Activity"",""id"":""https://w3id.or...",NaN,"{""objectType"":""Agent"",""name"":""New Client"",""mbo...",NaN
1,652d32344c323c03df9ca1dd,1.0.1,66ba3816-0f60-4776-bfdb-9836c02fd92a,2023-10-16T12:52:14.3070000Z,2023-10-16T12:53:07.826Z,C1E0F8B9,"{""id"":""http://adlnet.gov/expapi/verbs/interact...","{""objectType"":""Activity"",""id"":""https://spy.lip...",NaN,"{""objectType"":""Agent"",""name"":""New Client"",""mbo...",NaN
2,652d32344c323c03df9ca1dc,1.0.1,b344c16c-5223-46ec-a3f5-f6e73f5e0b19,2023-10-16T12:52:10.5780000Z,2023-10-16T12:53:07.826Z,C1E0F8B9,"{""id"":""http://adlnet.gov/expapi/verbs/interact...","{""objectType"":""Activity"",""id"":""https://spy.lip...",NaN,"{""objectType"":""Agent"",""name"":""New Client"",""mbo...",NaN
3,652d32344c323c03df9ca1db,1.0.1,4a6e5a4b-35a7-4c24-8b6f-554744fcef58,2023-10-16T12:52:08.8620000Z,2023-10-16T12:53:07.826Z,C1E0F8B9,"{""id"":""http://adlnet.gov/expapi/verbs/interact...","{""objectType"":""Activity"",""id"":""https://spy.lip...",NaN,"{""objectType"":""Agent"",""name"":""New Client"",""mbo...",NaN
4,652d32344c323c03df9ca1da,1.0.1,6d44d933-41af-40ed-8486-faeb72d28666,2023-10-16T12:52:07.6800000Z,2023-10-16T12:53:07.826Z,C1E0F8B9,"{""id"":""http://adlnet.gov/expapi/verbs/interact...","{""objectType"":""Activity"",""id"":""https://spy.lip...",NaN,"{""objectType"":""Agent"",""name"":""New Client"",""mbo...",NaN

In [43]:
# Temporary list of verbs
verbs = []

# Iterate over data
for index, row in spy_data.iterrows():
    # Create a json object from the verb column
    a = json.loads(row['verb'])
    # Append the name of the verb to the list
    verbs.append(a['display']['en-US'])

spy_data['verb'] = verbs

In [44]:
spy_data.head()

,_id,version,id,timestamp,stored,actor,verb,object,result,authority,context
0,652d32344c323c03df9ca1de,1.0.1,2ad6dd87-a685-4807-9365-5e47a09c0faf,2023-10-16T12:52:23.9850000Z,2023-10-16T12:53:07.826Z,C1E0F8B9,exited,"{""objectType"":""Activity"",""id"":""https://w3id.or...",NaN,"{""objectType"":""Agent"",""name"":""New Client"",""mbo...",NaN
1,652d32344c323c03df9ca1dd,1.0.1,66ba3816-0f60-4776-bfdb-9836c02fd92a,2023-10-16T12:52:14.3070000Z,2023-10-16T12:53:07.826Z,C1E0F8B9,interacted,"{""objectType"":""Activity"",""id"":""https://spy.lip...",NaN,"{""objectType"":""Agent"",""name"":""New Client"",""mbo...",NaN
2,652d32344c323c03df9ca1dc,1.0.1,b344c16c-5223-46ec-a3f5-f6e73f5e0b19,2023-10-16T12:52:10.5780000Z,2023-10-16T12:53:07.826Z,C1E0F8B9,interacted,"{""objectType"":""Activity"",""id"":""https://spy.lip...",NaN,"{""objectType"":""Agent"",""name"":""New Client"",""mbo...",NaN
3,652d32344c323c03df9ca1db,1.0.1,4a6e5a4b-35a7-4c24-8b6f-554744fcef58,2023-10-16T12:52:08.8620000Z,2023-10-16T12:53:07.826Z,C1E0F8B9,interacted,"{""objectType"":""Activity"",""id"":""https://spy.lip...",NaN,"{""objectType"":""Agent"",""name"":""New Client"",""mbo...",NaN
4,652d32344c323c03df9ca1da,1.0.1,6d44d933-41af-40ed-8486-faeb72d28666,2023-10-16T12:52:07.6800000Z,2023-10-16T12:53:07.826Z,C1E0F8B9,interacted,"{""objectType"":""Activity"",""id"":""https://spy.lip...",NaN,"{""objectType"":""Agent"",""name"":""New Client"",""mbo...",NaN

In [45]:
# Sort data by actor and timestamp in reverse order
spy_data = spy_data.sort_values(by=['actor', 'timestamp'], ascending=False)

In [56]:
all_levels = []
current_level = None

# Iterate over the actors
for actor in spy_data['actor'].unique():
    # Temporary list of levels
    levels = []
    # Iterate over the data of the actor backwards
    for index, row in spy_data[spy_data['actor'] == actor].iloc[::-1].iterrows():
        
        # If the verb of clean_spy_data using the index is 'launched'
        if row['verb'] == 'launched':
            # Convert the object column to a json object
            a = json.loads(row['object'])

            # Set the current level to the extension name without '.xml' at the end
            current_level = a['definition']['extensions']['https://spy&46;lip6&46;fr/xapi/extensions/value'][0][:-4]
            
        levels.append(current_level)
    
    all_levels.append(levels[::-1])

ValueError: Length of values (781) does not match length of index (327401)

In [59]:
# Add the levels backwards to the dataframes
spy_data['levels'] = all_levels

In [110]:
# Create a new dataframe with the columns we want from spy_data: actor, timestamp, stored, verb, levels
clean_spy_data = pd.DataFrame()
clean_spy_data['actor'] = spy_data['actor']
clean_spy_data['timestamp'] = spy_data['timestamp']
clean_spy_data['stored'] = spy_data['stored']
clean_spy_data['verb'] = spy_data['verb']
clean_spy_data['levels'] = spy_data['levels']
clean_spy_data['result'] = spy_data['result']
clean_spy_data['time'] = spy_data['time']

clean_spy_data.head()

,actor,timestamp,stored,verb,levels,result,time
288908,f10c3152,2023-03-17T13:49:01.7960000Z,2023-03-17T13:49:15.073Z,executed,levels/collaborateur/niveau03,,
288914,f10c3152,2023-03-17T13:48:57.6240000Z,2023-03-17T13:49:15.073Z,inserted,levels/collaborateur/niveau03,,
288930,f10c3152,2023-03-17T13:48:48.9860000Z,2023-03-17T13:49:15.073Z,inserted,levels/collaborateur/niveau03,,
288945,f10c3152,2023-03-17T13:48:41.1910000Z,2023-03-17T13:49:15.073Z,inserted,levels/collaborateur/niveau03,,
289002,f10c3152,2023-03-17T13:48:10.5390000Z,2023-03-17T13:49:15.073Z,inserted,levels/collaborateur/niveau03,,

In [111]:
clean_spy_data.to_csv('clean_spy_data.csv')

In [62]:
spy_data['result']

288908    NaN
288914    NaN
288930    NaN
288945    NaN
289002    NaN
         ...
201753    NaN
201785    NaN
201823    NaN
201833    NaN
201834    NaN
Name: result, Length: 327401, dtype: object

In [63]:
# Temporary list of results
results = []

# Iterate over data
for index, row in spy_data.iterrows():
    # If this is a completed verb
    if row['verb'] == 'completed':
        # Create a json object from the result column
        a = json.loads(row['result'])
        # Append the success value to the list
        results.append(a['success'])
    else:
        results.append('')

spy_data['result'] = results

In [69]:
# Check if all completed verbs have a result
spy_data[spy_data['verb'] == 'completed']['result'].value_counts()

True     15310
False     3620
Name: result, dtype: int64

In [108]:
# Temporary list of times
all_times = []

# Iterate over the actors
for actor in spy_data['actor'].unique():
    # Temporary list of levels
    times = []
    # Iterate over the data of the actor backwards
    for index, row in spy_data[spy_data['actor'] == actor].iloc[::-1].iterrows():
        
        # If the verb is 'completed'
        if row['verb'] == 'completed':
            # Store the timestamp as the end time and convert it to a datetime object
            end_time = pd.to_datetime(row['timestamp'])

            # Calculate the time taken and store it in the dataframe with the last completed verb
            times.append((end_time - start_time).total_seconds())

        # If the verb is 'launched'
        elif row['verb'] == 'launched':
            # Store the start time and convert it to a datetime object
            start_time = pd.to_datetime(row['timestamp'])
            times.append('')

        else:
            times.append('')
    
    all_times.append(times[::-1])

In [121]:
import datetime

In [113]:
spy_data = pd.read_csv('clean_spy_data.csv')

In [128]:
# Get the actor who has the longest time and convert the time in the format 'HH:MM:SS'
print('Longest time: ')
display(spy_data[spy_data['time'] == spy_data['time'].max()]['time'].apply(lambda x: str(datetime.timedelta(seconds=x))))
# Display the actor
display(spy_data[spy_data['time'] == spy_data['time'].max()]['actor'])

print('----------------------------------------')

# Get the actor who has the shortest time and convert the time in the format 'HH:MM:SS'
print('Shortest time: ')
display(spy_data[spy_data['time'] == spy_data['time'].min()]['time'].apply(lambda x: str(datetime.timedelta(seconds=x))))

Longest time:

58091    1 day, 17:43:33.291000
Name: time, dtype: object

58091    D4039AEB
Name: actor, dtype: object

----------------------------------------
Shortest time:

16877    0:00:00.215000
Name: time, dtype: object

Mean time: